apiVersion: apps/v1
kind: Deployment
metadata:
  name: sscms-deployment-core
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: sscms-core
        image: sscms/core:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: SSCMS_SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_SECURITY_KEY
        - name: SSCMS_DATABASE_TYPE
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_DATABASE_TYPE
        - name: SSCMS_DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_DATABASE_HOST
        - name: SSCMS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_DATABASE_USER
        - name: SSCMS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_DATABASE_PASSWORD
        - name: SSCMS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_DATABASE_NAME
        - name: SSCMS_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: sscms-secrets
              key: SSCMS_REDIS_HOST
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: sscms-config-maps
              key: ASPNETCORE_ENVIRONMENT
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: sscms-core-storage
          mountPath: /app/wwwroot/
      volumes:
      - name: sscms-core-storage
        persistentVolumeClaim:
          claimName: sscms-pv-claim