apiVersion: apps/v1
kind: Deployment
metadata:
  name: sscms-deployment-redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: sscms-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
        - containerPort: 6379